### ISSUE TITLE
broken in Julia v0.3

### ISSUE THREAD

**Issue by denizyuret** [JuliaGPU/CUDArt.jl#26]
When I start with a clean environment and try to add and use CUDArt to Julia3 I get the following error:
```
julia> using CUDArt
ERROR: Ref not defined
 in include at ./boot.jl:245
 in include_from_node1 at ./loading.jl:128
 in include at ./boot.jl:245
 in include_from_node1 at ./loading.jl:128
 in reload_path at loading.jl:152
 in _require at loading.jl:67
 in require at loading.jl:51
while loading /home/nlg-05/dy_052/julia-pkgdir/v0.3/CUDArt/src/stream.jl, in expression starting on line 46
while loading /home/nlg-05/dy_052/julia-pkgdir/v0.3/CUDArt/src/CUDArt.jl, in expression starting on line 53
```
Can we tell Julia3 to use an older version by default maybe?  Or use more Compat?  What is the right way to maintain a package to be compatible with multiple versions?  (I am asking because I need to keep a couple of packages functional in Julia3 and Julia4 for a while... :)

**Comment by timholy** [comment]
Oh, drat. Foiled by the fact that there is no travis testing.

Yes, we could tell it to use an older version; that would just mean modifying https://github.com/JuliaLang/METADATA.jl/blob/metadata-v2/CUDArt/versions/0.1.4/requires so that it requires `julia 0.4-` and submitting pull request.

Alternatively, maybe we should delete v0.1.4 and replace it with v0.2. That way there's room for the julia 0.3 series to keep improving. If you like that better, I can do that.

Finally, we could replace `Ref` with `[]` (i.e., a 0-dimensional array) on julia 0.3. However, I don't think there's any benefit for julia 0.3 with this most recent commit.

Which do you like best?

**Comment by denizyuret** [comment]
I think the first two suggestions are both good.  Going back on Ref is quicker fix but sooner or later we'd have to face this again with something else.  Better break our chains now...

**Comment by timholy** [comment]
Fixed by https://github.com/JuliaLang/METADATA.jl/pull/3429

I've also created a `julia-0.3` branch, so if you want to hack on julia 0.3 support that's the branch to start with.
