### ISSUE TITLE
clone into "CUDArt" folder instead of "CUDArt.jl"

### ISSUE THREAD

**Issue by Cody-G** [JuliaGPU/CUDArt.jl#6]
Currently the package gets cloned into a  "CUDArt.jl" directory and fails to build.  It turns out the build code looks for a "CUDArt" folder.  Renaming the folder after cloning is enough to allow me to build successfully.

**Comment by timholy** [comment]
Thanks for the report!

How did you clone it? If you use `Pkg.clone(url)`, I think the `.jl` gets stripped. If you use the command-line, I think you're right that it's necessary to give it a new name, like `git clone url CUDArt`. I think that's true for most julia packages, though, because they all (should) end in `.jl`.

**Comment by Cody-G** [comment]
Ah!  I used the command line.  That makes sense.  Thanks!
